name: qatra_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  country_code_picker: ^2.0.2
  flutter_screenutil: ^5.0.0+2
  sliding_sheet: ^0.5.0
  google_maps_flutter: ^0.5.24+1
  location: ^2.5.0
  get: ^4.3.8
  flutter_zoom_drawer: ^2.1.1
  dio: ^4.0.0
  json_serializable: ^5.0.2
  shared_preferences: ^2.0.8
  provider: ^6.0.1
  fluttertoast: ^8.0.8
  page_transition: "^2.0.4"
  flutter_progress_hud: ^2.0.0

  firebase_core: "^1.7.0"         #1.10.0
  firebase_auth: "^3.1.3"         #3.2.0
  firebase_database: "^8.1.0"     #up to date
  url_launcher: ^6.0.17


  uni_links: ^0.5.1
#  flutter_google_places: ^0.3.0
#  geocoder: ^0.2.1
  flutter_launcher_icons: ^0.9.2
  flutter_spinkit: ^5.1.0
  webview_flutter: ^3.0.0
  sn_progress_dialog: ^1.0.3



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo1.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - splash.png
    - logo.png
    - img1.png
    - img2.png
    - img3.png
    - pass.png
    - message.png
    - product.png
    - map_icon.png
    - rigth.png
    - payment.png
    - paypal.png
    - visa.png
    - visa1.png
    - mada_logo.png
    - apple_pay.png
    - backgrund.png
    - like.png
    - order_imag.png
    - home_img.png
    - user.png
    - menu.png
    - menu_home.png
    - qatra.png
    - policy.png
    - mayasem.png
    - benood.png
    - logout.png
    - home_unf.png
    - user_unf.png
    - order_f.png
    - logo1.png
    - loader_backinout.gif
    - assets/flags/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # app:
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/tajawal_regular.ttf
        - asset: assets/fonts/tajawal_light.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
